Config:
  #FfMpegHome: C:\\ProgramData\\chocolatey\\lib\\ffmpeg\\tools\\ffmpeg\\bin
  #FfMpegHome: .\\ffmpeg-master-latest-win64-gpl-shared\\bin
  FfMpegHome: .\\ffmpeg\\bin
  InputCsv: ./conf/example.csv
  Output:
    DirWav: ./temp
    DirOgg: ./output
    #AddLengthPostfix: true
    AddLengthPostfix: false
  TTS:
    Engine: Windows
    #Voice: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_ZIRA_11.0
    Voice: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-GB_HAZEL_11.0
  Audio:
    Volume: 0
    Filter:
      Apply: true
      #Apply: false
      Boost: 10
      ArgHighPass: 4000
      ArgLowPass: 3000
    #Trimm: true
    Trimm: false
    WhiteNoise:
      Add: true
      #Add: false
      VolumeDecrease: 35
    PreSound:
      Add: true
      #Add: false
      File: sounds/In.wav
    PostSound:
      Add: true
      #Add: false
      File: sounds/Out.wav
